### ISSUE TITLE
Unable to resolve host "api.storyblok.com"

### ISSUE THREAD

**Issue by daliborristic883** [mikepenz/storyblok-mp-SDK#83] opened 2022-05-03 22:28 UTC
## About this issue
I am getting this error from Firebase crashlytics.

```
Fatal Exception: java.net.UnknownHostException
Unable to resolve host "api.storyblok.com": No address associated with hostname
java.net.Inet6AddressImpl.lookupHostByName
keyboard_arrow_down
Caused by android.system.GaiException
android_getaddrinfo failed: EAI_NODATA (No address associated with hostname)
keyboard_arrow_up
libcore.io.Linux.android_getaddrinfo (Linux.java)
arrow_drop_down
com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getResponseCode (HttpsURLConnectionImpl.java:30)
arrow_right
io.ktor.client.engine.android.AndroidClientEngine$execute$2.invoke (AndroidClientEngine.kt:89)
io.ktor.client.engine.android.AndroidClientEngine$execute$2.invoke (AndroidClientEngine.kt:88)
io.ktor.client.engine.android.AndroidURLConnectionUtilsKt.timeoutAwareConnection (AndroidURLConnectionUtils.kt:55)
io.ktor.client.engine.android.AndroidClientEngine.execute (AndroidClientEngine.kt:88)
io.ktor.client.engine.HttpClientEngine$executeWithinCallContext$2.invokeSuspend (HttpClientEngine.kt:85)
kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith (ContinuationImpl.kt:33)
kotlinx.coroutines.DispatchedTask.run (DispatchedTask.kt:106)
kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely (CoroutineScheduler.kt:571)
kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask (CoroutineScheduler.kt:750)
kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker (CoroutineScheduler.kt:678)
kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run (CoroutineScheduler.kt:665)
```

Please see attached screenshot.

## Details
- [ ] Used library version: 1.3.0-rc01
- [ ] Used platform: Android
- [ ] Used support library version: true
- [ ] Used gradle build tools version: 7.0.4
- [ ] Used tooling / Android Studio version: Android Studio Bumblebee | 2021.1.1 Patch 1
- [ ] Other used libraries, potential conflicting libraries

![Screenshot 2022-05-04 at 12 28 13 AM](https://user-images.githubusercontent.com/65829381/166581449-e293ad8a-0026-4860-89bc-7c07ed137500.png)

**Comment by mikepenz** [comment] 2022-05-04 08:21
Any additional details on the environment? 

Without additional context, it looks like the phone was without connection while you tried to call the endpoint.

**Comment by daliborristic883** [comment] 2023-01-04 21:05
@mikepenz 
What additional details on the environment?

Please check this screenshot.
![Screenshot 2023-01-04 at 10 04 39 PM](https://user-images.githubusercontent.com/65829381/210649736-5314ff70-6e0e-436e-82df-0b5141428766.png)

**Comment by mikepenz** [comment] 2023-01-05 07:43
Based on the screenshots it seems that the device was either without internet (or the connection as bad to not do the hostname lookup) or (more unlikely) something in the network of device blocked the hostname lookup for the storyblok domain. 

Are you able to reproduce this in an environment in which you are certain the domain is accessible?


It's worth noting that the library does not include network availability checks as this is left for the host application to handle

**Comment by mikepenz** [comment] 2024-06-17 11:11
Closing due to in-activity. Please report back if that's still the case

**Closed by mikepenz** 2024-06-17 11:11 UTC
